let N = 34;
let K = 3.4;
let M = "Murali";
let k=undefined;
let n = NaN;
let bool = 5>1;
console.log(N);
console.log(typeof(N));
console.log(K);
console.log(typeof(K));
console.log(M);
console.log(typeof(M));
console.log(k);
console.log(typeof(k));
console.log(n);
console.log(typeof(n));
console.log(bool);
console.log(typeof(bool));
console.log(typeof(Math));
