console.log("Unary Operators");
console.log("+ 4 =",+4);
console.log("- 4 =",-4);
console.log("Binary operators");
console.log("Addition");
console.log("4 + 3 = ",4 + 3);
console.log("Subtraction");
console.log("4 - 3 =",4 - 3);
console.log("Multiplication");
console.log("4 * 3 =",4 * 3);
console.log("Division");
console.log("4 / 3 =",4/3);
console.log("power");
console.log("4 ** 4 =",4**4);
console.log("modulus");
console.log("4 % 3 =",4%3);
console.log("concatenation");
console.log(234+"234");
console.log("Increment/Decrement operators");
let count=0;
console.log(count++);
console.log(count--);
console.log(++count);
console.log(--count);
console.log("Bitwise operator");
console.log("4 & 3 = ",4&3);
console.log("4 | 3 = ",4|3);
console.log("4 ^ 3 = ",4^3);
console.log("4 >> 1 = ",4 >> 1);
console.log("4 << 1 = ",4 << 1);
console.log("~4 = ",~4);
